#!/bin/bash
#
# setup-unattended-upgrades.sh
#
# Configures Ubuntu Server for automatic security-only updates:
#   - Security updates only (no regular updates, no proposed, no backports)
#   - No automatic reboots
#   - Docker packages excluded from auto-updates
#   - Unused dependencies and old kernels auto-removed
#
# Usage:
#   sudo bash setup-unattended-upgrades.sh
#
# Safe to run multiple times (idempotent).
#

set -e

# Require root
if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run as root (use sudo)" >&2
    exit 1
fi

echo "=========================================="
echo " Unattended-Upgrades Setup"
echo " Host: $(hostname)"
echo " Date: $(date)"
echo "=========================================="
echo ""

# --- Step 1: Install required packages ---
echo "[1/5] Installing unattended-upgrades and apt-listchanges..."
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y unattended-upgrades apt-listchanges
echo "    Done."
echo ""

# --- Step 2: Back up existing configs ---
echo "[2/5] Backing up existing configuration..."
BACKUP_SUFFIX=".backup-$(date +%Y%m%d-%H%M%S)"

if [[ -f /etc/apt/apt.conf.d/50unattended-upgrades ]]; then
    cp /etc/apt/apt.conf.d/50unattended-upgrades \
       /etc/apt/apt.conf.d/50unattended-upgrades${BACKUP_SUFFIX}
    echo "    Backed up 50unattended-upgrades to 50unattended-upgrades${BACKUP_SUFFIX}"
fi

if [[ -f /etc/apt/apt.conf.d/20auto-upgrades ]]; then
    cp /etc/apt/apt.conf.d/20auto-upgrades \
       /etc/apt/apt.conf.d/20auto-upgrades${BACKUP_SUFFIX}
    echo "    Backed up 20auto-upgrades to 20auto-upgrades${BACKUP_SUFFIX}"
fi
echo ""

# --- Step 3: Write main config (50unattended-upgrades) ---
echo "[3/5] Writing /etc/apt/apt.conf.d/50unattended-upgrades..."
cat > /etc/apt/apt.conf.d/50unattended-upgrades <<'EOF'
// Automatically generated by setup-unattended-upgrades.sh
// Profile: Security-only, no auto-reboot, Docker excluded

Unattended-Upgrade::Allowed-Origins {
        "${distro_id}:${distro_codename}-security";
        "${distro_id}ESMApps:${distro_codename}-apps-security";
        "${distro_id}ESM:${distro_codename}-infra-security";
//      "${distro_id}:${distro_codename}-updates";
//      "${distro_id}:${distro_codename}-proposed";
//      "${distro_id}:${distro_codename}-backports";
};

// Packages that will NEVER be automatically upgraded.
// Docker is excluded to prevent unexpected daemon restarts affecting containers.
Unattended-Upgrade::Package-Blacklist {
    "docker-ce";
    "docker-ce-cli";
    "docker-ce-rootless-extras";
    "docker-buildx-plugin";
    "docker-compose-plugin";
    "containerd.io";
};

// Only run on AC power (not relevant for servers, but harmless)
Unattended-Upgrade::OnlyOnACPower "true";

// Don't run on metered connections
Unattended-Upgrade::Skip-Updates-On-Metered-Connections "true";

// Display upgraded packages in log output
Unattended-Upgrade::Verbose "false";

// Print debug info to log (useful for troubleshooting; set to true if needed)
Unattended-Upgrade::Debug "false";

// Remove unused automatically-installed kernel-related packages
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";

// Remove any new unused dependencies after the upgrade
Unattended-Upgrade::Remove-New-Unused-Dependencies "true";

// Remove any unused dependencies
Unattended-Upgrade::Remove-Unused-Dependencies "true";

// Automatically reboot - DISABLED per user config.
// To enable smart auto-reboots later, change "false" to "true" and uncomment the time.
Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Automatic-Reboot-WithUsers "false";
//Unattended-Upgrade::Automatic-Reboot-Time "04:00";

// Log to syslog in addition to /var/log/unattended-upgrades/
Unattended-Upgrade::SyslogEnable "true";
Unattended-Upgrade::SyslogFacility "daemon";

// Bandwidth limit (KB/s) - uncomment to enable
//Acquire::http::Dl-Limit "5000";

// Minimal steps - allows interruption via SIGTERM in a safe manner
Unattended-Upgrade::MinimalSteps "true";
EOF
echo "    Done."
echo ""

# --- Step 4: Write schedule config (20auto-upgrades) ---
echo "[4/5] Writing /etc/apt/apt.conf.d/20auto-upgrades..."
cat > /etc/apt/apt.conf.d/20auto-upgrades <<'EOF'
// Automatically generated by setup-unattended-upgrades.sh
// Runs apt update + unattended-upgrade daily; autocleans every 7 days.

APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF
echo "    Done."
echo ""

# --- Step 5: Validate and enable ---
echo "[5/5] Validating configuration and enabling timers..."

# Validate config by running a dry-run
if unattended-upgrade --dry-run --debug > /tmp/uu-dryrun.log 2>&1; then
    echo "    Config validation: PASSED"
else
    echo "    ERROR: Config validation FAILED. See /tmp/uu-dryrun.log" >&2
    tail -20 /tmp/uu-dryrun.log >&2
    exit 1
fi

# Enable timers
systemctl enable --now apt-daily.timer > /dev/null 2>&1
systemctl enable --now apt-daily-upgrade.timer > /dev/null 2>&1
systemctl enable --now unattended-upgrades.service > /dev/null 2>&1

echo "    Timers enabled."
echo ""

# --- Summary ---
echo "=========================================="
echo " Setup complete on $(hostname)"
echo "=========================================="
echo ""
echo "Timer status:"
systemctl list-timers 'apt-daily*' --no-pager
echo ""
echo "Logs will be written to:"
echo "  /var/log/unattended-upgrades/unattended-upgrades.log"
echo ""
echo "To manually run now (for testing):"
echo "  sudo unattended-upgrade -d"
echo ""
echo "To see packages that would be upgraded:"
echo "  sudo unattended-upgrade --dry-run --debug"
echo ""
echo "To check if a reboot is needed:"
echo "  [ -f /var/run/reboot-required ] && cat /var/run/reboot-required.pkgs || echo 'No reboot needed'"
echo ""
